"""
Central algorithm registry.
"""
from __future__ import annotations

from algorithms.domain_models.ecommerce_models import (
    run_ecommerce_popularity,
    run_ecommerce_purchase_als,
)
from algorithms.domain_models.movie_models import run_movie_item_knn, run_temporal_svd
from algorithms.explicit_models.nmf import run_nmf
from algorithms.explicit_models.svd import run_svd, run_svdpp
from algorithms.general_models import run_ease, run_item_knn, run_user_knn
from algorithms.hybrid_models import (
    run_autoencoder_cf,
    run_content_tfidf,
    run_factorization_machines,
    run_lightfm_hybrid,
)
from algorithms.implicit_models.als import run_als
from algorithms.implicit_models.bpr import run_bpr


ALGORITHM_REGISTRY: dict[str, dict] = {
    "SVD": {
        "fn": run_svd,
        "feedback": "both",
        "max_users": 25_000,
        "max_items": 15_000,
        "domain": "general",
        "description": "Truncated SVD matrix factorization (sparse-friendly).",
        "training_speed": "fast",
        "scalability": "high",
        "robustness": "high",
        "sparsity_fit": "high",
        "interpretability": "medium",
        "production_readiness": "high",
    },
    "SVD++": {
        "fn": run_svdpp,
        "feedback": "explicit",
        "max_users": 5_000,
        "max_items": 5_000,
        "domain": "general",
        "description": "SVD with implicit signal enrichment via SGD.",
        "training_speed": "slow",
        "scalability": "low",
        "robustness": "medium",
        "sparsity_fit": "medium",
        "interpretability": "medium",
        "production_readiness": "medium",
    },
    "NMF": {
        "fn": run_nmf,
        "feedback": "explicit",
        "max_users": 15_000,
        "max_items": 10_000,
        "domain": "general",
        "description": "Non-negative matrix factorization for interpretable factors.",
        "training_speed": "medium",
        "scalability": "medium",
        "robustness": "medium",
        "sparsity_fit": "medium",
        "interpretability": "high",
        "production_readiness": "high",
    },
    "ALS": {
        "fn": run_als,
        "feedback": "implicit",
        "max_users": None,
        "max_items": None,
        "domain": "general",
        "description": "Alternating Least Squares for implicit feedback.",
        "training_speed": "fast",
        "scalability": "high",
        "robustness": "high",
        "sparsity_fit": "high",
        "interpretability": "low",
        "production_readiness": "high",
    },
    "BPR": {
        "fn": run_bpr,
        "feedback": "implicit",
        "max_users": None,
        "max_items": None,
        "domain": "general",
        "description": "Bayesian Personalized Ranking for pairwise ranking quality.",
        "training_speed": "medium",
        "scalability": "high",
        "robustness": "medium",
        "sparsity_fit": "high",
        "interpretability": "low",
        "production_readiness": "high",
    },
    "Ecommerce-Popularity": {
        "fn": run_ecommerce_popularity,
        "feedback": "implicit",
        "max_users": None,
        "max_items": None,
        "domain": "ecommerce",
        "description": "Recency-weighted popularity baseline.",
        "training_speed": "fast",
        "scalability": "high",
        "robustness": "high",
        "sparsity_fit": "high",
        "interpretability": "high",
        "production_readiness": "high",
    },
    "Ecommerce-Purchase-ALS": {
        "fn": run_ecommerce_purchase_als,
        "feedback": "implicit",
        "max_users": None,
        "max_items": None,
        "domain": "ecommerce",
        "description": "ALS with purchase-weighted confidence.",
        "training_speed": "medium",
        "scalability": "high",
        "robustness": "high",
        "sparsity_fit": "high",
        "interpretability": "medium",
        "production_readiness": "high",
    },
    "Movie-Item-KNN": {
        "fn": run_movie_item_knn,
        "feedback": "explicit",
        "max_users": 20_000,
        "max_items": 10_000,
        "domain": "movie",
        "description": "Genre-aware item KNN with cosine similarity.",
        "training_speed": "medium",
        "scalability": "medium",
        "robustness": "medium",
        "sparsity_fit": "low",
        "interpretability": "high",
        "production_readiness": "medium",
    },
    "Temporal-SVD": {
        "fn": run_temporal_svd,
        "feedback": "both",
        "max_users": 25_000,
        "max_items": 12_000,
        "domain": "movie",
        "description": "Time-aware SVD to model preference drift.",
        "training_speed": "medium",
        "scalability": "medium",
        "robustness": "medium",
        "sparsity_fit": "medium",
        "interpretability": "medium",
        "production_readiness": "medium",
    },
    "User-KNN": {
        "fn": run_user_knn,
        "feedback": "both",
        "max_users": 12_000,
        "max_items": 20_000,
        "domain": "general",
        "description": "User-based nearest-neighbor collaborative filtering with cosine similarity.",
        "training_speed": "medium",
        "scalability": "medium",
        "robustness": "medium",
        "sparsity_fit": "medium",
        "interpretability": "high",
        "production_readiness": "medium",
    },
    "Item-KNN": {
        "fn": run_item_knn,
        "feedback": "both",
        "max_users": 20_000,
        "max_items": 12_000,
        "domain": "general",
        "description": "Item-based nearest-neighbor collaborative filtering with cosine similarity.",
        "training_speed": "medium",
        "scalability": "medium",
        "robustness": "high",
        "sparsity_fit": "medium",
        "interpretability": "high",
        "production_readiness": "high",
    },
    "EASE": {
        "fn": run_ease,
        "feedback": "both",
        "max_users": 50_000,
        "max_items": 8_000,
        "domain": "general",
        "description": "Embarrassingly Shallow Autoencoder solved as a closed-form linear recommender.",
        "training_speed": "fast",
        "scalability": "medium",
        "robustness": "high",
        "sparsity_fit": "high",
        "interpretability": "medium",
        "production_readiness": "high",
    },
    "LightFM": {
        "fn": run_lightfm_hybrid,
        "feedback": "both",
        "max_users": 20_000,
        "max_items": 8_000,
        "domain": "general",
        "description": "LightFM-style hybrid recommender blending collaborative and side-feature factors.",
        "training_speed": "medium",
        "scalability": "medium",
        "robustness": "medium",
        "sparsity_fit": "high",
        "interpretability": "medium",
        "production_readiness": "medium",
    },
    "Autoencoder-CF": {
        "fn": run_autoencoder_cf,
        "feedback": "both",
        "max_users": 6_000,
        "max_items": 3_000,
        "domain": "general",
        "description": "Shallow neural collaborative filtering autoencoder over the interaction matrix.",
        "training_speed": "slow",
        "scalability": "low",
        "robustness": "medium",
        "sparsity_fit": "medium",
        "interpretability": "low",
        "production_readiness": "medium",
    },
    "Content-Based TF-IDF": {
        "fn": run_content_tfidf,
        "feedback": "both",
        "max_users": 25_000,
        "max_items": 12_000,
        "domain": "general",
        "description": "Metadata-driven TF-IDF recommender with user content profiles for cold-start support.",
        "training_speed": "fast",
        "scalability": "medium",
        "robustness": "high",
        "sparsity_fit": "high",
        "interpretability": "high",
        "production_readiness": "high",
    },
    "Factorization Machines": {
        "fn": run_factorization_machines,
        "feedback": "both",
        "max_users": 15_000,
        "max_items": 8_000,
        "domain": "general",
        "description": "Feature-aware factorization machine style recommender for richer side-feature interactions.",
        "training_speed": "slow",
        "scalability": "medium",
        "robustness": "medium",
        "sparsity_fit": "high",
        "interpretability": "medium",
        "production_readiness": "medium",
    },
}

